name: 'Deploy a LAMP VM to Azure action'
description: 'This action helps create an Azure VM and deploy LAMP stack on it'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to login to azure'
    required: true
  tenant-id:
    description: 'Tenant id to login to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  resource-group-name:
    description: 'Resource group to deploy your resources to'
    required: true
  admin-username:
    description: 'Admin username to login to vm'
    required: true
  admin-password:
    description: 'Admin password to login to vm'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3
      
    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: false
        
    - name: Checkout Azure-Samples/azure-search-openai-demo repository
      uses: actions/checkout@v2
      with:
        repository: Azure-Samples/azure-search-openai-demo
        path: external-repo

    - name: Install azd
      uses: Azure/setup-azd@v0.1.0

    - name: Install Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Log in with Azure (Federated Credentials)
      run: |
        azd auth login `
          --client-id ${{ inputs.client-id }} `
          --federated-credential-provider "github" `
          --tenant-id ${{ inputs.tenant-id }}
      shell: pwsh
      
    - name: Create environment
        run: |
          azd env new testing-openai `
            --environment testing-openai `
            -- location eastus `

    - name: Set environment variables
      run: |
        azd env set AZURE_ENV_NAME testing-openai
        azd env set AZURE_LOCATION eastus
        azd env set AZURE_SUBSCRIPTION_ID ${{ inputs.subscription-id }}
        
    - name: Init Open AI Search Demo repo
      run: |
        azd up `
          --cwd external-repo `
          --environment testing-openai
        # azd init -t azure-search-openai-demo `
        #   --environment testing-openai `
        #   -- location eastus `
        #   -- subscription ${{ inputs.subscription-id }} `
        #   --no-prompt
      shell: pwsh

      
    
      
    
