name: 'Deploy a LAMP VM to Azure action'
description: 'This action helps create an Azure VM and deploy LAMP stack on it'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to log in to azure'
    required: true
  tenant-id:
    description: 'Tenant id to log in to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  resource-group-name:
    description: 'Resource group to deploy your resources to'
    required: true
  admin-username:
    description: 'Admin username to log in to vm'
    required: true
  admin-password:
    description: 'Admin password to log in to vm'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3

    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: false

    - name: Checkout Azure-Samples/azure-search-openai-demo repository
      uses: actions/checkout@v2
      with:
        repository: Azure-Samples/azure-search-openai-demo
        path: external-repo
  
    - name: Install azd
      uses: Azure/setup-azd@v0.1.0

    - name: Install Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Create directory
      run: |
        chdir azd-repo
      shell: pwsh

    - name: Change directory
      run: |
        chdir azd-repo
      shell: pwsh
      
    - name: List directories
      run: |
        dir
      shell: pwsh
      
    - name: Provision Infrastructure
      run: azd init -t Azure-Samples/azure-search-openai-demo --no-prompt
      env:
        AZURE_ENV_NAME: ${{ inputs.resource-group-name }}
        AZURE_LOCATION: 'eastus'
        AZURE_SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
      shell: pwsh

    # - name: Deploy Application
    #   run: azd deploy --no-prompt
    #   env:
    #     AZURE_ENV_NAME: ${{ inputs.resource-group-name }}
    #     AZURE_LOCATION: 'eastus'
    #     AZURE_SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
    #   shell: pwsh
