name: 'Deploy a Open AI Model to Azure action'
description: 'This action helps create an OpenAI search model'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to log in to azure'
    required: true
  tenant-id:
    description: 'Tenant id to log in to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  resource-group-name:
    description: 'Resource group to deploy your resources to'
    required: true
  location:
    description: 'Location to deploy OpenAI resource to'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3

    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: false
  
    - name: Install azd
      uses: Azure/setup-azd@v0.1.0

    - name: Install Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Create directory
      run: |
        mkdir azd-repo
      shell: pwsh

    - name: Change directory
      run: |
        cd azd-repo
      shell: pwsh
      
    - name: List directories
      run: |
        dir
      shell: pwsh

    - name: Log in with Azure (Federated Credentials)
      run: |
        azd auth login `
          --client-id ${{ inputs.client-id }} `
          --federated-credential-provider "github" `
          --tenant-id ${{ inputs.tenant-id }}
      shell: pwsh

      
    - name: Initialize Application
      run: azd init -t Azure-Samples/azure-search-openai-demo --no-prompt
      working-directory: azd-repo
      env:
        AZURE_ENV_NAME: ${{ inputs.resource-group-name }}
        AZURE_LOCATION: ${{ inputs.location }}
        AZURE_SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
        AZURE_RESOURCE_GROUP: ${{ inputs.resource-group-name }}
      shell: pwsh

    - name: Deploy Application
      run: azd up
      working-directory: azd-repo
      env:
        AZURE_ENV_NAME: ${{ inputs.resource-group-name }}
        AZURE_LOCATION: ${{ inputs.location }}
        AZURE_SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
        AZURE_RESOURCE_GROUP: ${{ inputs.resource-group-name }}
      shell: pwsh
